require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WikipagesController do

  # This should return the minimal set of attributes required to create a valid
  # Wikipage. As you add validations to Wikipage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "wiki_id" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WikipagesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all wikipages as @wikipages" do
      wikipage = Wikipage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:wikipages).should eq([wikipage])
    end
  end

  describe "GET show" do
    it "assigns the requested wikipage as @wikipage" do
      wikipage = Wikipage.create! valid_attributes
      get :show, {:id => wikipage.to_param}, valid_session
      assigns(:wikipage).should eq(wikipage)
    end
  end

  describe "GET new" do
    it "assigns a new wikipage as @wikipage" do
      get :new, {}, valid_session
      assigns(:wikipage).should be_a_new(Wikipage)
    end
  end

  describe "GET edit" do
    it "assigns the requested wikipage as @wikipage" do
      wikipage = Wikipage.create! valid_attributes
      get :edit, {:id => wikipage.to_param}, valid_session
      assigns(:wikipage).should eq(wikipage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Wikipage" do
        expect {
          post :create, {:wikipage => valid_attributes}, valid_session
        }.to change(Wikipage, :count).by(1)
      end

      it "assigns a newly created wikipage as @wikipage" do
        post :create, {:wikipage => valid_attributes}, valid_session
        assigns(:wikipage).should be_a(Wikipage)
        assigns(:wikipage).should be_persisted
      end

      it "redirects to the created wikipage" do
        post :create, {:wikipage => valid_attributes}, valid_session
        response.should redirect_to(Wikipage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wikipage as @wikipage" do
        # Trigger the behavior that occurs when invalid params are submitted
        Wikipage.any_instance.stub(:save).and_return(false)
        post :create, {:wikipage => { "wiki_id" => "invalid value" }}, valid_session
        assigns(:wikipage).should be_a_new(Wikipage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Wikipage.any_instance.stub(:save).and_return(false)
        post :create, {:wikipage => { "wiki_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested wikipage" do
        wikipage = Wikipage.create! valid_attributes
        # Assuming there are no other wikipages in the database, this
        # specifies that the Wikipage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Wikipage.any_instance.should_receive(:update_attributes).with({ "wiki_id" => "1" })
        put :update, {:id => wikipage.to_param, :wikipage => { "wiki_id" => "1" }}, valid_session
      end

      it "assigns the requested wikipage as @wikipage" do
        wikipage = Wikipage.create! valid_attributes
        put :update, {:id => wikipage.to_param, :wikipage => valid_attributes}, valid_session
        assigns(:wikipage).should eq(wikipage)
      end

      it "redirects to the wikipage" do
        wikipage = Wikipage.create! valid_attributes
        put :update, {:id => wikipage.to_param, :wikipage => valid_attributes}, valid_session
        response.should redirect_to(wikipage)
      end
    end

    describe "with invalid params" do
      it "assigns the wikipage as @wikipage" do
        wikipage = Wikipage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Wikipage.any_instance.stub(:save).and_return(false)
        put :update, {:id => wikipage.to_param, :wikipage => { "wiki_id" => "invalid value" }}, valid_session
        assigns(:wikipage).should eq(wikipage)
      end

      it "re-renders the 'edit' template" do
        wikipage = Wikipage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Wikipage.any_instance.stub(:save).and_return(false)
        put :update, {:id => wikipage.to_param, :wikipage => { "wiki_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wikipage" do
      wikipage = Wikipage.create! valid_attributes
      expect {
        delete :destroy, {:id => wikipage.to_param}, valid_session
      }.to change(Wikipage, :count).by(-1)
    end

    it "redirects to the wikipages list" do
      wikipage = Wikipage.create! valid_attributes
      delete :destroy, {:id => wikipage.to_param}, valid_session
      response.should redirect_to(wikipages_url)
    end
  end

end
